# Generated by Django 4.0.2 on 2022-02-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_talk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_owner',
            new_name='owner',
        ),
    ]
